name: morning
on:
  schedule:
  - cron:  '38 23 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    container: node:16.16.0
    name: send morning to your girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master
    
    # - name: Remove old artifacts
     #  uses: c-hive/gha-remove-artifacts@v1
      # with:
       #  age: '15 days' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5

    - name: sender
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        architecture: 'x64'
        
    - run: pip install --upgrade pip
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      USER_ID: ${{ secrets.USER_ID }}
      USER_ID1: ${{ secrets.USER_ID1 }}
      START_DATE: ${{ secrets.START_DATE }}
      BIRTHDAY: ${{ secrets.BIRTHDAY }}
      CITY: ${{ secrets.CITY }}
